// Global variables that are set and used
// across the application
let verticesSize,
  vertices,
  adapter,
  context,
  colorAttachment,
  colorTextureView,
  colorTexture,
  depthTexture,
  code,
  shaderDesc,
  colorState,
  shaderModule,
  pipeline,
  renderPassDesc,
  commandEncoder,
  passEncoder,
  device,
  drawingTop,
  drawingLeft,
  canvas,
  bary,
  points,
  uniformValues,
  uniformBindGroup,
  indices,
  uvs,
  trans,
  modelViewMatrix,
  imageSource,
  objModels,
  texture;
